### ISSUE TITLE
FR: multiSelect or mix and match input and select in multiInput

### ISSUE THREAD

**Issue by jcurtis-cc** [Araxeus/custom-electron-prompt#6]
Awesome extension of electron-prompt!

Being able to mix and match `select` with `input` in a multiinput would be ideal - or is this already supported?

**Comment by Araxeus** [comment]
Sorry but mixing prompt styles is not supported (yet), all prompts have a single purpose right now

If you want, you could try making such an option 🙂

**Comment by jcurtis-cc** [comment]
Cool :) I’ve added this to a branch here https://github.com/lysdexic-audio/custom-electron-prompt/tree/flexible-inputs

Think it makes more sense than making another `promptCreateMultiSelect` and a `promptCreateMixedMultiInput`

I’ll make a screenshot and PR if you’re happy to go this way ^_^

**Comment by Araxeus** [comment]
Look great to me, just nit style thing in the example you added to readme:

the `height` param should be removed from this example since 150 is too low and the default is fine

also the "value" attribute needs some more spaces before it, so you could use

```js
prompt({
    title: "credentials",
    label: "Login Info:",
    type: "multiInput",
    multiInputOptions:
        [
            {
                inputAttrs:
                {
                    type: "email",
                    required: true,
                    placeholder: "email"
                }
            },
            {
                inputAttrs:
                {
                    type: "password",
                    placeholder: "password"
                }
            },
            {
                selectOptions: { na: "North America", eu: "Europe", other: "Other" },
				value: "2"
            }
        ],
    resizable: true,
    width: 300,
}, win).then(input => console.log(`input == ${input}`)).catch(console.error)
```

also in `prompt.js` replace lines 83-94 with
```js
	if (promptOptions.type !== "multiInput") {
		if (promptOptions.type !== "keybind") {
			dataElement.setAttribute("id", "data");

			if (promptOptions.type !== "counter") {
				dataContainerElement.append(dataElement);
			}

			if (promptOptions.type !== "select") {
				dataElement.select();
			}
		}

		dataElement.focus?.();
	}
``` 
or something along this lines to stop the program from trying to select/focus the last element in the multiInput
(which causes an error if the last element is a `select` element and it tries to select it, all I had to do was reorder the example your provided)


anyhow you're welcome to open a PR, and propose any changes you deem appropriate

**Comment by jcurtis-cc** [comment]
yeah caught that after i committed haha! annoyed me too. will update and PR tomorrow 👍

**Comment by Araxeus** [comment]
Added in #7
